h2015_index:
  path: /
  defaults: { _controller: AppBundle:Default:homepage}
  options:
    expose: true

h2015_wishlist:
    path: /wishlist
    defaults: { _controller: AppBundle:Default:wishlist}
    options:
      expose: true