h2015_index:
  path: /
  defaults: { _controller: AppBundle:Default:homepage}
  options:
    expose: true

h2015_wishlist:
    path: /wishlist
    defaults: { _controller: AppBundle:Default:wishlist}
    options:
      expose: true

h2015_wishlist_add:
    path: /wishlist-add
    defaults: { _controller: AppBundle:Default:wishlistAdd}
    options:
      expose: true

h2015_wishlist_remove:
    path: /wishlist-remove
    defaults: { _controller: AppBundle:Default:wishlistRemove}
    options:
      expose: true

h2015_offers:
    path: /offers
    defaults: { _controller: AppBundle:Default:offers}
    options:
      expose: true